"""Unit tests for the spec-driven Taichi carrier emitter (Task P4-1).

Covers :mod:`mechdsl.lawgen.carrier_emitter`: the class emitter that assembles a
complete Taichi module (``class <Name>`` + ``@ti.func`` methods) from a
:class:`~mechdsl.lawgen.contracts.PlasticityCarrierSpec`, mapping bare lowered
symbol names onto the Cycle 0 contract (parameters → ``self.<param>``, variables →
method args) and auto-differentiating each factor for its ``get_d*`` method.

The tests are structural / golden-string and numerical-substitute assertions on
the emitted module string — no Taichi JIT here (that is the guarded smoke test in
the generated file and the P4-2 equivalence gate). They pin: the contract surface,
the symbol → self.<param> rebinding, per-method independence, the neutral H/Q
factors, the import-only-Taichi invariant, and byte-determinism.
"""

from __future__ import annotations

import math

import pytest
import sympy as sp

from mechdsl.lawgen.carrier_emitter import (
    _assert_taichi_only,
    emit_carrier,
    snake_case_module_name,
)
from mechdsl.lawgen.contracts import PlasticityCarrierSpec
from mechdsl.lawgen.diagnostics import LawgenError
from mechdsl.lawgen.manifest import GENERATED_BY

# The canonical SwiftVoce input-formula hash (used only as a banner stamp here —
# the emitter records it verbatim, it does not recompute it).
_HASH = "7b5af3a8bb79c2e44e0055a7076dd2c9de2ce8c75eb2e262b80bb4e0232d557f"


def _swift_voce_spec() -> PlasticityCarrierSpec:
    """The canonical SwiftVoce carrier spec (neutral H/Q factors)."""
    sigma0, Q, b, K, n, p0 = sp.symbols("sigma0 Q b K n p0")
    p, edot, T = sp.symbols("p edot T")
    R = sigma0 + Q * (1 - sp.exp(-b * p)) + K * ((p + p0) ** n - p0**n)
    return PlasticityCarrierSpec(
        name="SwiftVoce",
        parameters=("sigma0", "Q", "b", "K", "n", "p0"),
        expressions={"R": R, "H": sp.Integer(1), "Q": sp.Integer(1)},
        variable_bindings={"p": p, "edot": edot, "T": T},
    )


def _emit_swift_voce() -> str:
    return emit_carrier(_swift_voce_spec(), source_hash=_HASH, generated_by=GENERATED_BY).source


class TestSnakeCaseModuleName:
    def test_camelcase_to_snake(self) -> None:
        assert snake_case_module_name("SwiftVoce") == "swift_voce"

    def test_already_snake_is_lowercased_unchanged(self) -> None:
        assert snake_case_module_name("linear_min") == "linear_min"

    def test_digit_and_acronym_boundaries(self) -> None:
        assert snake_case_module_name("J2Plasticity") == "j2_plasticity"


class TestEmittedContract:
    def test_banner_stamps_hash_and_generator(self) -> None:
        source = _emit_swift_voce()
        assert source.splitlines()[0] == (
            f"# AUTO-GENERATED by {GENERATED_BY}. source_hash: {_HASH}"
        )

    def test_class_and_decorator(self) -> None:
        source = _emit_swift_voce()
        assert "@ti.data_oriented" in source
        assert "class SwiftVoce:" in source

    def test_all_contract_methods_present(self) -> None:
        source = _emit_swift_voce()
        for signature in (
            "def __init__(self, params_dict, ti_type=ti.f64):",
            "def get_R(self, peeq, yield_scale: ti.f64 = 1.0):",
            "def get_dR(self, peeq, yield_scale: ti.f64 = 1.0):",
            "def get_H(self, edot):",
            "def get_dH(self, edot):",
            "def get_Q(self, T):",
            "def get_dQ(self, T):",
            "def eval_components(self, peeq, edot, T, yield_scale: ti.f64 = 1.0):",
        ):
            assert signature in source, signature

    def test_eval_components_returns_six_tuple_in_order(self) -> None:
        source = _emit_swift_voce()
        assert "return R, rate, thermal, dR, drate, dthermal" in source

    def test_init_binds_every_parameter_to_self(self) -> None:
        source = _emit_swift_voce()
        for param in ("sigma0", "Q", "b", "K", "n", "p0"):
            assert f'self.{param} = float(params_dict["{param}"])' in source


class TestSymbolRebinding:
    def test_parameters_become_self_attributes(self) -> None:
        source = _emit_swift_voce()
        # get_R references material params via self.<param>, never bare.
        assert "self.sigma0" in source
        assert "self.Q" in source
        assert "self.p0" in source

    def test_plastic_strain_is_emitted_as_peeq(self) -> None:
        source = _emit_swift_voce()
        # The spec binds ``p``; the emitted get_R argument + body use ``peeq``.
        assert "def get_R(self, peeq" in source
        # The bare spec symbol ``p`` must not leak into get_R as a standalone name
        # (only ``peeq`` / ``self.<param>`` appear). Guard against a stray ``* p``.
        get_r_body = source.split("def get_R", 1)[1].split("def get_dR", 1)[0]
        assert "peeq" in get_r_body

    def test_yield_scale_wraps_R_and_dR_only(self) -> None:
        source = _emit_swift_voce()
        get_r = source.split("def get_R", 1)[1].split("def get_dR", 1)[0]
        get_dr = source.split("def get_dR", 1)[1].split("def get_H", 1)[0]
        get_h = source.split("def get_H", 1)[1].split("def get_dH", 1)[0]
        assert "return yield_scale * (" in get_r
        assert "return yield_scale * (" in get_dr
        # get_H takes no yield scale.
        assert "yield_scale" not in get_h


class TestNeutralFactors:
    def test_H_and_Q_are_neutral_and_derivatives_zero(self) -> None:
        source = _emit_swift_voce()

        def _method_body(name: str, until: str) -> str:
            return source.split(f"def {name}(", 1)[1].split(f"def {until}(", 1)[0]

        # H, Q are the neutral factors (== 1); their derivatives are 0. Each body's
        # single return statement is exactly the neutral literal.
        assert "return 1" in _method_body("get_H", "get_dH")
        assert "return 0" in _method_body("get_dH", "get_Q")
        assert "return 1" in _method_body("get_Q", "get_dQ")
        assert "return 0" in _method_body("get_dQ", "eval_components")
        # And the neutral bodies carry no material-parameter reference (a stray
        # ``self.<param>`` in a neutral factor would signal a rebinding leak).
        assert "self." not in _method_body("get_H", "get_dH")
        assert "self." not in _method_body("get_Q", "get_dQ")


class TestImportInvariant:
    def test_only_taichi_imported(self) -> None:
        source = _emit_swift_voce()
        import_lines = [
            line.strip()
            for line in source.splitlines()
            if line.strip().startswith(("import ", "from "))
        ]
        assert import_lines == ["import taichi as ti"]

    def test_no_forbidden_import_in_emitted_source(self) -> None:
        source = _emit_swift_voce()
        for forbidden in ("import sympy", "import mechdsl", "import ticonstit"):
            assert forbidden not in source

    @pytest.mark.parametrize(
        "bad_import",
        [
            "import sympy",
            "import mechdsl as m",
            "from mechdsl.lawgen import cli",
            "import ticonstit",
            "from ticonstit.generated import x",
            "import numerixweave",
        ],
    )
    def test_assert_taichi_only_raises_on_forbidden_import(self, bad_import: str) -> None:
        # Directly exercise the fail-loud self-check raise path (the guard that runs
        # on the emitter's own output): a module carrying any forbidden
        # import — the offline generator (sympy/mechdsl) or the consumer
        # (ticonstit/numerixweave) — must raise AssertionError naming the module.
        source = f"import taichi as ti\n{bad_import}\n\n\nclass Bad:\n    pass\n"
        with pytest.raises(AssertionError, match="forbidden module"):
            _assert_taichi_only(source, "Bad")

    def test_assert_taichi_only_accepts_taichi_and_stdlib(self) -> None:
        # The guard must NOT trip on Taichi or a stdlib import (e.g. math).
        source = "import taichi as ti\nimport math\n\n\nclass Ok:\n    pass\n"
        _assert_taichi_only(source, "Ok")  # returns None, does not raise


class TestDerivativeCorrectness:
    """dR is d(R)/d(peeq): prove the emitted derivative equals the analytic one.

    The emitter auto-differentiates R w.r.t. the plastic strain. Batched CSE would
    reorganise the structure, but per-method lowering keeps it clean; either way
    the value must match K*n*(p+p0)**(n-1) + Q*b*exp(-b*p) to machine precision.
    """

    def test_emitted_dR_matches_analytic_derivative(self) -> None:
        params = {"sigma0": 2.5e8, "Q": 1.2e8, "b": 15.0, "K": 3.0e8, "n": 0.3, "p0": 1e-4}

        def analytic_dr(peeq: float) -> float:
            base = max(peeq + params["p0"], 1e-12)
            return params["Q"] * params["b"] * math.exp(-params["b"] * peeq) + params["K"] * params[
                "n"
            ] * base ** (params["n"] - 1.0)

        # Re-implement the emitted dR structure (CSE temp x0 + guarded division).
        def emitted_dr(peeq: float) -> float:
            x0 = peeq + params["p0"]
            sel = max(x0, 1e-12) if x0 >= 0 else min(x0, -1e-12)
            swift = params["K"] * params["n"] * max(x0, 1e-12) ** params["n"] / sel
            return swift + params["Q"] * params["b"] * math.exp(-params["b"] * peeq)

        for peeq in (1e-3, 1e-2, 0.1, 0.5, 1.0, 1.5):
            assert math.isclose(emitted_dr(peeq), analytic_dr(peeq), rel_tol=1e-10)


class TestDeterminism:
    def test_emission_is_byte_stable(self) -> None:
        assert _emit_swift_voce() == _emit_swift_voce()


class TestFailLoud:
    def test_unsupported_node_raises_lawgen_error(self) -> None:
        # A factor using a function outside the Taichi allow-list (erf) must fail
        # loud through the lowerer's collect-all LawgenError — no partial emit.
        x = sp.Symbol("p")
        a = sp.Symbol("a")
        spec = PlasticityCarrierSpec(
            name="Bad",
            parameters=("a",),
            expressions={"R": sp.erf(a * x), "H": sp.Integer(1), "Q": sp.Integer(1)},
            variable_bindings={"p": x, "edot": sp.Symbol("edot"), "T": sp.Symbol("T")},
        )
        with pytest.raises(LawgenError):
            emit_carrier(spec, source_hash=_HASH, generated_by=GENERATED_BY)
