"""Create the 9 Phase-1 task issues for plan 'back2latex' in dependency order.

Reads task JSONs from dev/tasks/back2latex/json/, builds a body via the task_issue
template fields, calls `gh issue create`, and records each issue number back into:
  - dev/tasks/back2latex/github_issue_map.json (phases.1.task_issues map)
  - the task JSON's github_issue.task_issue field
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TASKS = ROOT / "dev" / "tasks" / "back2latex"
JSONS = TASKS / "json"
MAP = TASKS / "github_issue_map.json"
PLAN = "dev/plans/back2latex.md"
SLUG = "back2latex"
PHASE = 1
PHASE_ISSUE = 125

# Dependency-respecting order (in-phase blockers must exist before their dependents).
ORDER = ["P1-1", "P1-4", "P1-8", "P1-2", "P1-9", "P1-3", "P1-5", "P1-6", "P1-7"]


def build_body(task: dict, blocker_issue_map: dict[str, int]) -> str:
    tid = task["task_id"]
    title = task["title"]
    objective = task["objective"]
    plan_lines = task["plan_lines"]
    tier = task["test_plan"]["tier"]
    impl = task["implementation_steps"]
    deliverables = task["deliverables"]
    accept = task["acceptance_criteria"]
    test_artifacts = task["test_artifacts"]
    verif_cmds = task["verification_commands"]
    risks = task["risks"]
    blocked_by = task["blocked_by"]

    parts: list[str] = []
    parts.append(f"## {tid}: {title}")
    parts.append("")
    parts.append(f"**Phase:** {PHASE} — Apply structural amendments to recovery_plan_latex_contract.md (see #{PHASE_ISSUE})")
    parts.append(f"**Plan source:** `{PLAN}` lines {plan_lines[0]}-{plan_lines[1]}")
    parts.append(f"**Task JSON:** `dev/tasks/{SLUG}/json/{tid}.json`")
    parts.append(f"**Tier:** {tier}")
    parts.append("")
    parts.append("### Objective")
    parts.append(objective)
    parts.append("")
    parts.append("### Implementation Steps")
    for i, step in enumerate(impl, 1):
        parts.append(f"{i}. {step}")
    parts.append("")
    parts.append("### Deliverables")
    for d in deliverables:
        parts.append(f"- {d}")
    parts.append("")
    parts.append("### Acceptance Criteria")
    parts.append("")
    parts.append("#### Test stubs (generated by scaffold)")
    for ta in test_artifacts:
        parts.append(f"- [ ] `{ta}` — see test docstrings for the exact case wording")
    parts.append("")
    parts.append("#### Additional criteria")
    for c in accept:
        parts.append(f"- [ ] {c}")
    parts.append("")
    parts.append("### Verification Commands")
    parts.append("```bash")
    for cmd in verif_cmds:
        if cmd:
            parts.append(cmd)
    parts.append("```")
    parts.append("")
    parts.append("### Risks")
    for r in risks:
        parts.append(f"- {r}")
    parts.append("")
    parts.append("### Blocked By")
    if blocked_by:
        for b in blocked_by:
            issue_num = blocker_issue_map.get(b)
            ref = f"#{issue_num}" if issue_num else "(blocker not yet created)"
            parts.append(f"- Blocked by {ref} ({b})")
    else:
        parts.append("None — can start immediately")
    parts.append("")
    parts.append("### Agent Dispatch")
    parts.append("```")
    parts.append("Read this issue and implement it.")
    parts.append(f"Task JSON: dev/tasks/{SLUG}/json/{tid}.json")
    parts.append("```")
    return "\n".join(parts)


def main() -> None:
    issue_map_data = json.loads(MAP.read_text())
    blocker_issue_map: dict[str, int] = {}

    bodies_dir = ROOT / ".context" / "issue_bodies" / "back2latex_phase1"
    bodies_dir.mkdir(parents=True, exist_ok=True)

    for tid in ORDER:
        task_path = JSONS / f"{tid}.json"
        task = json.loads(task_path.read_text())

        body = build_body(task, blocker_issue_map)
        body_file = bodies_dir / f"{tid}.md"
        body_file.write_text(body)

        tier = task["test_plan"]["tier"]
        labels = f"task-issue,phase-{PHASE},plan:{SLUG}"
        if tier in ("unit", "integration", "regression"):
            labels += f",tier:{tier}"
        if task["blocked_by"]:
            unresolved = any(
                b not in blocker_issue_map for b in task["blocked_by"]
            ) or any(
                json.loads((JSONS / f"{b}.json").read_text())["status"] != "done"
                for b in task["blocked_by"]
            )
            if unresolved:
                labels += ",blocked"

        title = f"[{SLUG}] {tid}: {task['title']}"
        cmd = [
            "gh", "issue", "create",
            "--title", title,
            "--label", labels,
            "--body-file", str(body_file),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        url = result.stdout.strip()
        issue_num = int(url.rsplit("/", 1)[-1])
        blocker_issue_map[tid] = issue_num
        print(f"{tid} -> #{issue_num}")

        task["github_issue"]["task_issue"] = issue_num
        task_path.write_text(json.dumps(task, indent=4) + "\n")

        issue_map_data["phases"][str(PHASE)]["task_issues"][tid] = issue_num
        MAP.write_text(json.dumps(issue_map_data, indent=2) + "\n")


if __name__ == "__main__":
    main()
