"""Create the 4 Phase-2 task issues for plan 'back2latex' in dependency order.

Mirrors .context/scaffold_phase1_create_issues.py but for Phase 2.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TASKS = ROOT / "dev" / "tasks" / "back2latex"
JSONS = TASKS / "json"
MAP = TASKS / "github_issue_map.json"
PLAN = "dev/plans/back2latex.md"
SLUG = "back2latex"
PHASE = 2
PHASE_ISSUE = 126

ORDER = ["P2-1", "P2-2", "P2-3", "P2-4"]


def build_body(task: dict, blocker_issue_map: dict[str, int]) -> str:
    tid = task["task_id"]
    title = task["title"]
    objective = task["objective"]
    plan_lines = task["plan_lines"]
    tier = task["test_plan"]["tier"]
    impl = task["implementation_steps"]
    deliverables = task["deliverables"]
    accept = task["acceptance_criteria"]
    test_artifacts = task["test_artifacts"]
    verif_cmds = task["verification_commands"]
    risks = task["risks"]
    blocked_by = task["blocked_by"]

    parts: list[str] = []
    parts.append(f"## {tid}: {title}")
    parts.append("")
    parts.append(
        f"**Phase:** {PHASE} — Verify and validate via Aut_Faciam round-trip (see #{PHASE_ISSUE})"
    )
    parts.append(f"**Plan source:** `{PLAN}` lines {plan_lines[0]}-{plan_lines[1]}")
    parts.append(f"**Task JSON:** `dev/tasks/{SLUG}/json/{tid}.json`")
    parts.append(f"**Tier:** {tier}")
    parts.append("")
    parts.append("### Objective")
    parts.append(objective)
    parts.append("")
    parts.append("### Implementation Steps")
    for i, step in enumerate(impl, 1):
        parts.append(f"{i}. {step}")
    parts.append("")
    parts.append("### Deliverables")
    for d in deliverables:
        parts.append(f"- {d}")
    parts.append("")
    parts.append("### Acceptance Criteria")
    parts.append("")
    parts.append("#### Test stubs (generated by scaffold)")
    for ta in test_artifacts:
        parts.append(f"- [ ] `{ta}` — see test docstrings for the exact case wording")
    parts.append("")
    parts.append("#### Additional criteria")
    for c in accept:
        parts.append(f"- [ ] {c}")
    parts.append("")
    parts.append("### Verification Commands")
    parts.append("```bash")
    for cmd in verif_cmds:
        if cmd:
            parts.append(cmd)
    parts.append("```")
    parts.append("")
    parts.append("### Risks")
    for r in risks:
        parts.append(f"- {r}")
    parts.append("")
    parts.append("### Blocked By")
    if blocked_by:
        # Phase-2 tasks can be blocked by Phase-1 (already-done) tasks.
        for b in blocked_by:
            issue_num = blocker_issue_map.get(b)
            if issue_num is None:
                parts.append(f"- {b} (in-phase blocker not yet created)")
            else:
                parts.append(f"- Blocked by #{issue_num} ({b})")
    else:
        parts.append("None — can start immediately")
    parts.append("")
    parts.append("### Agent Dispatch")
    parts.append("```")
    parts.append("Read this issue and implement it.")
    parts.append(f"Task JSON: dev/tasks/{SLUG}/json/{tid}.json")
    parts.append("```")
    return "\n".join(parts)


def main() -> None:
    issue_map_data = json.loads(MAP.read_text())
    blocker_issue_map: dict[str, int] = dict(issue_map_data["phases"]["1"]["task_issues"])

    bodies_dir = ROOT / ".context" / "issue_bodies" / "back2latex_phase2"
    bodies_dir.mkdir(parents=True, exist_ok=True)

    for tid in ORDER:
        task_path = JSONS / f"{tid}.json"
        task = json.loads(task_path.read_text())
        body = build_body(task, blocker_issue_map)
        body_file = bodies_dir / f"{tid}.md"
        body_file.write_text(body)

        tier = task["test_plan"]["tier"]
        labels = f"task-issue,phase-{PHASE},plan:{SLUG}"
        if tier in ("unit", "integration", "regression"):
            labels += f",tier:{tier}"

        # blocked label if any blocker is not yet done
        unresolved = False
        for b in task["blocked_by"]:
            if b in blocker_issue_map:
                # phase 1 blocker — check task JSON status
                blocker_json = JSONS / f"{b}.json"
                if blocker_json.is_file():
                    blocker_data = json.loads(blocker_json.read_text())
                    if blocker_data.get("status") != "done":
                        unresolved = True
                        break
            else:
                unresolved = True
                break
        if unresolved:
            labels += ",blocked"

        title = f"[{SLUG}] {tid}: {task['title']}"
        cmd = [
            "gh",
            "issue",
            "create",
            "--title",
            title,
            "--label",
            labels,
            "--body-file",
            str(body_file),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        url = result.stdout.strip()
        issue_num = int(url.rsplit("/", 1)[-1])
        blocker_issue_map[tid] = issue_num
        print(f"{tid} -> #{issue_num}")

        task["github_issue"]["task_issue"] = issue_num
        task_path.write_text(json.dumps(task, indent=4) + "\n")

        issue_map_data["phases"][str(PHASE)]["task_issues"][tid] = issue_num
        MAP.write_text(json.dumps(issue_map_data, indent=2) + "\n")


if __name__ == "__main__":
    main()
