"""Recursive ScaffoldPhase 1 against the recovery plan.

Generates pytest stubs for the 6 recovery-plan Phase-1 tasks, updates each
task JSON with test_artifacts + verification_commands, writes a scaffold
validation report, creates 6 task issues on GitHub, populates the phase-1
issue body, and flips not-scaffolded -> scaffolded.

Hard stop: this script does NOT invoke /Aut_Faciam exec 1.
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TASKS = ROOT / "dev" / "tasks" / "recovery_plan_latex_contract"
JSON_DIR = TASKS / "json"
MAP_PATH = TASKS / "github_issue_map.json"
STUBS_DIR = (
    ROOT / "packages" / "mechdsl-core" / "tests" / "plan_tests" / "recovery_plan_latex_contract"
)
SLUG = "recovery-plan-latex-contract"
PHASE = 2


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, capture_output=True, text=True, check=True)


def write_stub(task: dict) -> Path:
    tid = task["task_id"]
    cases = task["test_plan"]["cases"]
    tier = task["test_plan"].get("tier", "docs")
    marker = "audit" if tier in ("docs", "manual") else tier
    body = [
        '"""Stub for ' + tid + ": " + task["title"][:80] + '."""',
        "from __future__ import annotations",
        "",
        "import pytest",
        "",
        "",
        f"class TestTask{tid.replace('-', '_')}:",
        '    """',
        f"    Tests for Task {tid}: {task['title'][:80]}",
        f"    Tier: {tier}",
        '    """',
        "",
    ]
    if not cases or all(not c.strip() for c in cases):
        cases = [f"{tid} acceptance criteria"]
    for i, case in enumerate(cases, 1):
        # Normalise to a short slug for the function name
        slug_text = case.lower()
        for ch in " :,.!?'`/():\"":
            slug_text = slug_text.replace(ch, "_")
        slug = "".join(c if c.isalnum() or c == "_" else "_" for c in slug_text)
        slug = "_".join(filter(None, slug.split("_")))[:50] or f"case_{i}"
        body.extend(
            [
                f"    @pytest.mark.{marker}",
                f"    def test_{slug}(self) -> None:",
                f'        """{case}"""',
                f'        pytest.skip("stub — implement after Task {tid} is complete")',
                "",
            ]
        )
    text = "\n".join(body) + "\n"
    out = STUBS_DIR / f"test_p2_{tid.split('-')[1]}.py"
    out.write_text(text)
    return out


def update_task_json(
    task_path: Path, stub_path: Path, repo: str, phase_issue: int, task_issue: int | None
) -> None:
    data = json.loads(task_path.read_text())
    rel = stub_path.relative_to(ROOT).as_posix()
    data["test_artifacts"] = [rel]
    tier = data["test_plan"].get("tier", "docs")
    marker = "audit" if tier in ("docs", "manual") else tier
    data["verification_commands"] = [f"uv run pytest {rel} -v -m {marker}"]
    data["github_issue"]["phase_issue"] = phase_issue
    if task_issue is not None:
        data["github_issue"]["task_issue"] = task_issue
    data["github_issue"]["repo"] = repo
    task_path.write_text(json.dumps(data, indent=4) + "\n")


def task_issue_body(task: dict, blocker_map: dict[str, int]) -> str:
    tid = task["task_id"]
    parts = [
        f"## {tid}: {task['title']}",
        "",
        f"**Phase:** 2 — Restore the frontend as the canonical entry point (R1) (see #{task['github_issue']['phase_issue']})",
        f"**Plan source:** `{task['plan_file']}` lines {task['plan_lines'][0]}-{task['plan_lines'][1]}",
        f"**Task JSON:** `dev/tasks/recovery_plan_latex_contract/json/{tid}.json`",
        f"**Tier:** {task['test_plan']['tier']}",
        "",
        "### Objective",
        task["objective"],
        "",
        "### Implementation Steps",
    ]
    for i, step in enumerate(task["implementation_steps"], 1):
        parts.append(f"{i}. {step}")
    parts.append("")
    parts.append("### Deliverables")
    for d in task["deliverables"]:
        parts.append(f"- {d}")
    parts.append("")
    parts.append("### Acceptance Criteria")
    parts.append("")
    parts.append("#### Test stubs (generated by scaffold)")
    for ta in task["test_artifacts"]:
        parts.append(f"- [ ] `{ta}` — see test docstrings for the exact case wording")
    parts.append("")
    parts.append("#### Additional criteria")
    for c in task["acceptance_criteria"]:
        parts.append(f"- [ ] {c}")
    parts.append("")
    parts.append("### Verification Commands")
    parts.append("```bash")
    for cmd in task["verification_commands"]:
        if cmd:
            parts.append(cmd)
    parts.append("```")
    parts.append("")
    parts.append("### Risks")
    for r in task["risks"]:
        parts.append(f"- {r}")
    parts.append("")
    parts.append("### Blocked By")
    if task["blocked_by"]:
        for b in task["blocked_by"]:
            issue_num = blocker_map.get(b)
            ref = f"#{issue_num}" if issue_num else "(blocker not yet created)"
            parts.append(f"- Blocked by {ref} ({b})")
    else:
        parts.append("None — can start immediately")
    parts.append("")
    parts.append("### Agent Dispatch")
    parts.append("```")
    parts.append("Read this issue and implement it.")
    parts.append(f"Task JSON: dev/tasks/recovery_plan_latex_contract/json/{tid}.json")
    parts.append("```")
    return "\n".join(parts)


def main() -> None:
    issue_map = json.loads(MAP_PATH.read_text())
    phase_issue = issue_map["phases"][str(PHASE)]["issue_number"]
    repo = issue_map["repo"]

    # Scaffold validation report
    validation_lines = [
        "# Phase 2 Scaffold Validation",
        "",
        "| Task ID | Title | Missing / Incomplete Fields | Scaffold Action |",
        "|---------|-------|-----------------------------|-----------------|",
    ]
    bodies_dir = ROOT / ".context" / "issue_bodies" / "recovery_phase1_tasks"
    bodies_dir.mkdir(parents=True, exist_ok=True)

    # Dependency-respecting order:
    #   P2-1 first (blocks P2-2/P2-3/P2-5/P2-6)
    #   P2-4 independent (docs)
    #   P2-2 + P2-3 depend on P2-1
    #   P2-5 depends on P2-1, P2-3
    #   P2-6 depends on P2-1, P2-5
    order = ["P2-1", "P2-4", "P2-2", "P2-3", "P2-5", "P2-6"]
    blocker_map: dict[str, int] = {}

    total_cases = 0
    for tid in order:
        task_path = JSON_DIR / f"{tid}.json"
        task = json.loads(task_path.read_text())
        stub_path = write_stub(task)
        update_task_json(task_path, stub_path, repo, phase_issue, None)
        cases = task["test_plan"]["cases"]
        total_cases += len(cases) if cases else 1
        validation_lines.append(f"| {tid} | {task['title'][:60]} | none | passthrough |")

    # Scaffold summary
    validation_lines.extend(
        [
            "",
            "## Scaffold Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            "| Tasks scaffolded | 6 |",
            f"| Test cases assessed | {total_cases} |",
            "| Cases covered by existing tests | 0 |",
            "| New stubs generated | " + str(total_cases) + " |",
            "| New stub files | 6 |",
            "| Tasks needing human review | 0 |",
            "",
            "## Notes",
            "",
            "- All Phase-1 recovery-plan tasks are docs-tier; stubs use `@pytest.mark.audit`.",
            "- Stubs currently `pytest.skip(...)` and become live assertions when each task lands.",
            "- Compressed-exec convention: all 6 Phase-2 tasks land on a single branch with one commit each, then a phase-end Gate B/C.",
        ]
    )
    (TASKS / "Phase_1_Scaffold_Validation.md").write_text("\n".join(validation_lines) + "\n")

    # Create task issues
    for tid in order:
        task_path = JSON_DIR / f"{tid}.json"
        task = json.loads(task_path.read_text())
        # Re-read to pick up the latest test_artifacts
        body = task_issue_body(task, blocker_map)
        body_path = bodies_dir / f"{tid}.md"
        body_path.write_text(body)

        labels = f"task-issue,phase-1,plan:{SLUG}"
        if task["blocked_by"]:
            labels += ",blocked"
        title = f"[{SLUG}] {tid}: {task['title']}"
        result = run(
            [
                "gh",
                "issue",
                "create",
                "--title",
                title,
                "--label",
                labels,
                "--body-file",
                str(body_path),
            ]
        )
        url = result.stdout.strip()
        issue_num = int(url.rsplit("/", 1)[-1])
        blocker_map[tid] = issue_num
        print(f"{tid} -> #{issue_num}")

        # Stamp task JSON with the issue number
        task["github_issue"]["task_issue"] = issue_num
        task_path.write_text(json.dumps(task, indent=4) + "\n")
        issue_map["phases"][str(PHASE)]["task_issues"][tid] = issue_num
        MAP_PATH.write_text(json.dumps(issue_map, indent=2) + "\n")

    # Populate the phase-1 issue and swap labels
    body_lines = [
        "## Phase 1: Freeze the contract surface (R0)",
        "",
        "**Status:** ✅ Scaffolded",
        f"**Plan overview:** #{issue_map['plan_overview_issue']}",
        "",
        "### Scaffold Summary",
        "| Metric | Value |",
        "|--------|-------|",
        "| Tasks scaffolded | 6 |",
        f"| Test cases assessed | {total_cases} |",
        "| Cases covered by existing tests | 0 |",
        f"| New stubs generated | {total_cases} |",
        "| Tasks needing human review | 0 |",
        "",
        "### Tasks",
    ]
    for tid in order:
        issue_num = blocker_map[tid]
        task = json.loads((JSON_DIR / f"{tid}.json").read_text())
        body_lines.append(f"- [ ] #{issue_num} — {tid}: {task['title']}")
    body_lines.append("")
    body_lines.append("### Phase Context Summary")
    body_lines.append((TASKS / "Phase_1_context_summary.md").read_text(encoding="utf-8"))
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as f:
        f.write("\n".join(body_lines))
        body_path = f.name
    run(
        [
            "gh",
            "issue",
            "edit",
            str(phase_issue),
            "--remove-label",
            "not-scaffolded",
            "--add-label",
            "scaffolded",
            "--body-file",
            body_path,
        ]
    )
    print(f"phase-1 issue #{phase_issue} populated and label-swapped")


if __name__ == "__main__":
    main()
