"""Recursive ScaffoldPhase 4 against the recovery plan.

Reads the 5 recovery-plan Phase-4 task JSONs (already populated with
test_artifacts + verification_commands by the surrounding scaffold pass),
creates 5 task issues on GitHub in dependency order, populates the
phase-4 issue body, and flips not-scaffolded -> scaffolded.

Hard stop: this script does NOT invoke /Aut_Faciam exec 4.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TASKS = ROOT / "dev" / "tasks" / "recovery_plan_latex_contract"
JSON_DIR = TASKS / "json"
MAP_PATH = TASKS / "github_issue_map.json"
SLUG = "recovery-plan-latex-contract"
PHASE = 4
PHASE_TITLE = "Phase 4 — Enrich `ElementIR` and normalize lowering boundaries (R3)"
ORDER = ["P4-1", "P4-2", "P4-3", "P4-4", "P4-5"]


def run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, capture_output=True, text=True, check=True)


def task_issue_body(task: dict, blocker_map: dict[str, int]) -> str:
    tid = task["task_id"]
    parts = [
        f"## {tid}: {task['title']}",
        "",
        f"**Phase:** 4 — Enrich `ElementIR` and normalize lowering boundaries (R3) "
        f"(see #{task['github_issue']['phase_issue']})",
        f"**Plan source:** `{task['plan_file']}` lines {task['plan_lines'][0]}-{task['plan_lines'][1]}",
        f"**Task JSON:** `dev/tasks/recovery_plan_latex_contract/json/{tid}.json`",
        f"**Tier:** {task['test_plan']['tier']}",
        "",
        "### Objective",
        task["objective"],
        "",
        "### Implementation Steps",
    ]
    for i, step in enumerate(task["implementation_steps"], 1):
        parts.append(f"{i}. {step}")
    parts.append("")
    parts.append("### Deliverables")
    for d in task["deliverables"]:
        parts.append(f"- {d}")
    parts.append("")
    parts.append("### Acceptance Criteria")
    parts.append("")
    parts.append("#### Test stubs (generated by scaffold)")
    for ta in task["test_artifacts"]:
        if ta:
            parts.append(f"- [ ] `{ta}` — see test docstrings for the exact case wording")
    parts.append("")
    parts.append("#### Additional criteria")
    for c in task["acceptance_criteria"]:
        parts.append(f"- [ ] {c}")
    parts.append("")
    parts.append("### Verification Commands")
    parts.append("```bash")
    for cmd in task["verification_commands"]:
        if cmd:
            parts.append(cmd)
    parts.append("```")
    parts.append("")
    parts.append("### Risks")
    for r in task["risks"]:
        parts.append(f"- {r}")
    parts.append("")
    parts.append("### Blocked By")
    if task["blocked_by"]:
        for b in task["blocked_by"]:
            issue_num = blocker_map.get(b)
            ref = f"#{issue_num}" if issue_num else "(blocker not yet created or out-of-phase)"
            parts.append(f"- Blocked by {ref} ({b})")
    else:
        parts.append("None — can start immediately")
    parts.append("")
    parts.append("### Agent Dispatch")
    parts.append("```")
    parts.append("Read this issue and implement it.")
    parts.append(f"Task JSON: dev/tasks/recovery_plan_latex_contract/json/{tid}.json")
    parts.append("```")
    return "\n".join(parts)


def cross_phase_blocker_issue(map_data: dict, blocker_id: str) -> int | None:
    """Find a blocker's GH issue number across all already-created phases."""
    for phase_data in map_data["phases"].values():
        if blocker_id in phase_data.get("task_issues", {}):
            return phase_data["task_issues"][blocker_id]
    return None


def main() -> None:
    issue_map = json.loads(MAP_PATH.read_text())
    phase_issue = issue_map["phases"][str(PHASE)]["issue_number"]
    repo = issue_map["repo"]

    # Build a starting blocker_map from previously-created issues (e.g. P3-1
    # in phase 3) so cross-phase Blocked-by references resolve.
    blocker_map: dict[str, int] = {}
    for phase_data in issue_map["phases"].values():
        for tid, num in phase_data.get("task_issues", {}).items():
            blocker_map[tid] = num

    bodies_dir = ROOT / ".context" / "issue_bodies" / "recovery_phase4_tasks"
    bodies_dir.mkdir(parents=True, exist_ok=True)

    for tid in ORDER:
        task_path = JSON_DIR / f"{tid}.json"
        task = json.loads(task_path.read_text())
        body = task_issue_body(task, blocker_map)
        body_path = bodies_dir / f"{tid}.md"
        body_path.write_text(body)

        labels = f"task-issue,phase-4,plan:{SLUG},tier:{task['test_plan']['tier']}"
        # Flag blocked if any blocker is not yet done.
        if task["blocked_by"]:
            unresolved = []
            for b in task["blocked_by"]:
                blocker_path = JSON_DIR / f"{b}.json"
                if blocker_path.exists():
                    blocker_status = json.loads(blocker_path.read_text())["status"]
                    if blocker_status != "done":
                        unresolved.append(b)
                else:
                    unresolved.append(b)
            if unresolved:
                labels += ",blocked"

        title = f"[{SLUG}] {tid}: {task['title']}"
        result = run(
            [
                "gh",
                "issue",
                "create",
                "--title",
                title,
                "--label",
                labels,
                "--body-file",
                str(body_path),
            ]
        )
        url = result.stdout.strip()
        issue_num = int(url.rsplit("/", 1)[-1])
        blocker_map[tid] = issue_num
        print(f"{tid} -> #{issue_num}")

        task["github_issue"]["task_issue"] = issue_num
        task_path.write_text(json.dumps(task, indent=4) + "\n")
        issue_map["phases"][str(PHASE)]["task_issues"][tid] = issue_num
        MAP_PATH.write_text(json.dumps(issue_map, indent=2) + "\n")

    # Populate the phase-4 issue body and flip the label.
    plan_overview = issue_map["plan_overview_issue"]
    phase_body_lines = [
        f"## {PHASE_TITLE}",
        "",
        "**Status:** ✅ Scaffolded",
        f"**Plan overview:** #{plan_overview}",
        "",
        "### Scaffold Summary",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Tasks scaffolded | {len(ORDER)} |",
        "| Test cases assessed | 10 |",
        "| Cases covered by existing tests | 0 |",
        "| New stubs generated | 10 |",
        "| New stub files | 5 |",
        "| Tasks needing human review | 0 |",
        "",
        "### Tasks (dependency order)",
    ]
    for tid in ORDER:
        task = json.loads((JSON_DIR / f"{tid}.json").read_text())
        phase_body_lines.append(
            f"- [ ] #{task['github_issue']['task_issue']} — {tid}: {task['title']}"
        )
    phase_body_lines.extend(
        [
            "",
            "### Phase Context Summary",
            "",
            "<details>",
            "<summary>Click to expand</summary>",
            "",
            (TASKS / "Phase_4_context_summary.md").read_text(),
            "",
            "</details>",
        ]
    )

    phase_body_path = bodies_dir / "phase4_body.md"
    phase_body_path.write_text("\n".join(phase_body_lines))
    run(
        [
            "gh",
            "issue",
            "edit",
            str(phase_issue),
            "--remove-label",
            "not-scaffolded",
            "--add-label",
            "scaffolded",
            "--body-file",
            str(phase_body_path),
        ]
    )
    print(f"Phase 4 issue #{phase_issue} populated and labelled scaffolded.")


if __name__ == "__main__":
    main()
