"""ti-runtime — neutral Taichi runtime for MechDSL-generated code (PlanJune14 PJ-0).

Seams + primitives only; algorithmic bodies are generated by algo2code and injected.
See the module-level READMEs for the Seams & Bodies contract.
"""

from __future__ import annotations

__version__ = "0.2.0"

from . import fields, hex8, seams, tensor_ti, vector_ops
from .seams import (
    AccelSolve,
    DiagonalPreconditioner,
    IdentityPreconditioner,
    Integrator,
    LinearSolveContext,
    Operator,
    PreconditionerBase,
    Solver,
    TimeIntegrationContext,
)
from .vector_ops import axpy, copy, dot, ediv, norm2, scal, vec_add, xpay, zero

__all__ = [
    "AccelSolve",
    "DiagonalPreconditioner",
    "IdentityPreconditioner",
    "Integrator",
    "LinearSolveContext",
    "Operator",
    "PreconditionerBase",
    "Solver",
    "TimeIntegrationContext",
    "axpy",
    "copy",
    "dot",
    "ediv",
    "fields",
    "hex8",
    "norm2",
    "scal",
    "seams",
    "tensor_ti",
    "vec_add",
    "vector_ops",
    "xpay",
    "zero",
]
