"""Tests for artifact bundle serialisation and golden-file regression.

Golden files are generated by ``tests/generate_golden.py`` and stored in
``tests/golden/`` as compressed numpy archives (.npz).  These tests verify
that fresh reference solver runs produce output matching the stored golden
data to within numerical tolerance.

Regenerate golden files intentionally with:
    PYTHONPATH=packages/mechdsl-core uv run python packages/mechdsl-core/tests/generate_golden.py
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np
import pytest

from mechdsl.symbolic.models.j2_power_law import J2PowerLawMaterial
from tests.ref.ref_hex8_elastic import generate_hex8_mesh, solve_elastic
from tests.ref.ref_hex8_plastic import solve_plastic

if TYPE_CHECKING:
    from pathlib import Path

    from numpy.typing import NDArray


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Tolerance for displacement comparison (spec: < 1e-10 relative).
_RTOL_DISP = 1e-10
_ATOL_DISP = 1e-14  # absolute floor for near-zero values
# Newton residual tails are sensitive to BLAS / platform roundoff once the solve
# is already in the ~1e-11 range, so keep a tiny absolute floor for the final
# iterations while preserving strict relative checks on the larger entries.
_RTOL_RESIDUAL = 1e-8
_ATOL_RESIDUAL = 2e-11


def _load_golden(golden_dir: Path, name: str) -> dict[str, NDArray]:
    """Load a golden .npz file and return its contents as a dict.

    Raises
    ------
    FileNotFoundError
        With a clear message pointing to the regeneration script.
    """
    path = golden_dir / name
    if not path.exists():
        msg = (
            f"Golden file not found: {path}\n"
            "Regenerate with:\n"
            "  PYTHONPATH=packages/mechdsl-core "
            "uv run python packages/mechdsl-core/tests/generate_golden.py"
        )
        raise FileNotFoundError(msg)
    return dict(np.load(path, allow_pickle=False))


def _run_elastic_cantilever() -> tuple[NDArray, list[float], NDArray, NDArray]:
    """Reproduce the elastic cantilever problem from golden generation.

    Returns (displacement, residual_history, coords, conn).
    """
    nx, ny, nz = 4, 2, 1
    Lx, Ly, Lz = 4.0, 2.0, 1.0
    coords, conn = generate_hex8_mesh(nx, ny, nz, Lx, Ly, Lz)
    n_nodes = coords.shape[0]

    E_young = 200.0e3
    nu = 0.3
    lam = E_young * nu / ((1 + nu) * (1 - 2 * nu))
    mu = E_young / (2 * (1 + nu))

    bc_mask = np.zeros((n_nodes, 3), dtype=bool)
    bc_values = np.zeros((n_nodes, 3), dtype=np.float64)
    left_nodes = np.where(np.abs(coords[:, 0]) < 1e-12)[0]
    bc_mask[left_nodes, :] = True

    f_ext = np.zeros((n_nodes, 3), dtype=np.float64)
    right_top = np.where(
        (np.abs(coords[:, 0] - Lx) < 1e-12)
        & (np.abs(coords[:, 1] - Ly) < 1e-12)
        & (np.abs(coords[:, 2] - Lz) < 1e-12)
    )[0]
    assert len(right_top) == 1
    f_ext[right_top[0], 2] = -10.0

    u, residuals = solve_elastic(
        coords,
        conn,
        lam,
        mu,
        bc_mask,
        bc_values,
        f_ext,
        tol=1e-8,
        max_iter=50,
        cg_tol=1e-10,
        cg_max_iter=2000,
    )
    return u, residuals, coords, conn


def _run_plastic_uniaxial() -> tuple[NDArray, NDArray, list[list[float]], NDArray, NDArray]:
    """Reproduce the plastic uniaxial problem from golden generation.

    Returns (displacement, alpha, residual_history, coords, conn).
    """
    nx, ny, nz = 2, 1, 1
    Lx, Ly, Lz = 2.0, 1.0, 1.0
    coords, conn = generate_hex8_mesh(nx, ny, nz, Lx, Ly, Lz)
    n_nodes = coords.shape[0]

    mat = J2PowerLawMaterial(E=200.0e3, nu=0.3, sigma_y0=250.0, K=1000.0, n=1.0)

    bc_mask = np.zeros((n_nodes, 3), dtype=bool)
    bc_values = np.zeros((n_nodes, 3), dtype=np.float64)
    left_nodes = np.where(np.abs(coords[:, 0]) < 1e-12)[0]
    bc_mask[left_nodes, :] = True

    right_nodes = np.where(np.abs(coords[:, 0] - Lx) < 1e-12)[0]
    bc_mask[right_nodes, 0] = True
    bc_values[right_nodes, 0] = 0.005 * Lx

    f_ext = np.zeros((n_nodes, 3), dtype=np.float64)

    u, history, residual_history = solve_plastic(
        coords,
        conn,
        mat,
        bc_mask,
        bc_values,
        f_ext,
        n_steps=5,
        tol=1e-8,
        max_iter=50,
        cg_tol=1e-10,
        cg_max_iter=2000,
    )
    return u, history.alpha_current, residual_history, coords, conn


# ===========================================================================
# Test 1: Golden files exist
# ===========================================================================


class TestGoldenFilesExist:
    """Verify golden artifact files are present."""

    def test_golden_elastic_exists(self, golden_dir: Path) -> None:
        """Golden file for elastic cantilever must exist."""
        path = golden_dir / "elastic_cantilever.npz"
        assert path.exists(), (
            f"Missing golden file: {path}\n"
            "Run: PYTHONPATH=packages/mechdsl-core "
            "uv run python packages/mechdsl-core/tests/generate_golden.py"
        )

    def test_golden_plastic_exists(self, golden_dir: Path) -> None:
        """Golden file for plastic uniaxial must exist."""
        path = golden_dir / "plastic_uniaxial.npz"
        assert path.exists(), (
            f"Missing golden file: {path}\n"
            "Run: PYTHONPATH=packages/mechdsl-core "
            "uv run python packages/mechdsl-core/tests/generate_golden.py"
        )

    def test_golden_necking_bar_exists(self, golden_dir: Path) -> None:
        """Golden file for necking bar reference must exist (P3-3).

        Verifies: reference data file exists with expected filename.
        Acceptance criterion: P3-3 AC1.
        Passes when: necking_bar_reference.npz is present in golden dir.
        """
        path = golden_dir / "necking_bar_reference.npz"
        assert path.exists(), (
            f"Missing golden file: {path}\n"
            "Run: PYTHONPATH=packages/mechdsl-core "
            "uv run python packages/mechdsl-core/tests/generate_golden.py"
        )


# ===========================================================================
# Test 2: Elastic golden regression
# ===========================================================================


class TestGoldenElasticMatches:
    """Fresh elastic solver run must match the stored golden data."""

    def test_golden_elastic_displacement(self, golden_dir: Path) -> None:
        """Displacement field matches golden to < 1e-10 relative tolerance."""
        golden = _load_golden(golden_dir, "elastic_cantilever.npz")
        u_fresh, _res, _coords, _conn = _run_elastic_cantilever()

        np.testing.assert_allclose(
            u_fresh,
            golden["displacement"],
            rtol=_RTOL_DISP,
            atol=_ATOL_DISP,
            err_msg="Elastic displacement field does not match golden data",
        )

    def test_golden_elastic_residual_history(self, golden_dir: Path) -> None:
        """Residual history matches golden (same convergence path)."""
        golden = _load_golden(golden_dir, "elastic_cantilever.npz")
        _u, residuals_fresh, _coords, _conn = _run_elastic_cantilever()

        residuals_arr = np.array(residuals_fresh, dtype=np.float64)
        np.testing.assert_allclose(
            residuals_arr,
            golden["residual_history"],
            rtol=_RTOL_RESIDUAL,
            atol=_ATOL_RESIDUAL,
            err_msg="Elastic residual history does not match golden data",
        )

    def test_golden_elastic_mesh_unchanged(self, golden_dir: Path) -> None:
        """Mesh (coords + connectivity) in golden file is consistent."""
        golden = _load_golden(golden_dir, "elastic_cantilever.npz")
        _u, _res, coords_fresh, conn_fresh = _run_elastic_cantilever()

        np.testing.assert_array_equal(
            coords_fresh,
            golden["coords"],
            err_msg="Mesh coordinates differ from golden — problem setup changed?",
        )
        np.testing.assert_array_equal(
            conn_fresh,
            golden["conn"],
            err_msg="Element connectivity differs from golden — problem setup changed?",
        )


# ===========================================================================
# Test 3: Plastic golden regression
# ===========================================================================


class TestGoldenPlasticMatches:
    """Fresh plastic solver run must match the stored golden data."""

    def test_golden_plastic_displacement(self, golden_dir: Path) -> None:
        """Displacement field matches golden to < 1e-10 relative tolerance."""
        golden = _load_golden(golden_dir, "plastic_uniaxial.npz")
        u_fresh, _alpha, _res, _coords, _conn = _run_plastic_uniaxial()

        np.testing.assert_allclose(
            u_fresh,
            golden["displacement"],
            rtol=_RTOL_DISP,
            atol=_ATOL_DISP,
            err_msg="Plastic displacement field does not match golden data",
        )

    def test_golden_plastic_alpha(self, golden_dir: Path) -> None:
        """Equivalent plastic strain matches golden."""
        golden = _load_golden(golden_dir, "plastic_uniaxial.npz")
        _u, alpha_fresh, _res, _coords, _conn = _run_plastic_uniaxial()

        np.testing.assert_allclose(
            alpha_fresh,
            golden["alpha"],
            rtol=_RTOL_DISP,
            atol=_ATOL_DISP,
            err_msg="Plastic alpha (equiv. plastic strain) does not match golden data",
        )

    def test_golden_plastic_residual_history(self, golden_dir: Path) -> None:
        """Residual history per step matches golden."""
        golden = _load_golden(golden_dir, "plastic_uniaxial.npz")
        _u, _alpha, residuals_fresh, _coords, _conn = _run_plastic_uniaxial()

        # Reconstruct flat residual array
        flat_fresh = np.concatenate([np.array(step, dtype=np.float64) for step in residuals_fresh])
        step_lengths_fresh = np.array([len(step) for step in residuals_fresh], dtype=np.int64)

        np.testing.assert_array_equal(
            step_lengths_fresh,
            golden["residual_step_lengths"],
            err_msg="Number of Newton iterations per step differs from golden",
        )
        np.testing.assert_allclose(
            flat_fresh,
            golden["residual_flat"],
            rtol=_RTOL_RESIDUAL,
            atol=_ATOL_RESIDUAL,
            err_msg="Plastic residual history does not match golden data",
        )

    def test_golden_plastic_mesh_unchanged(self, golden_dir: Path) -> None:
        """Mesh in golden file is consistent with fresh generation."""
        golden = _load_golden(golden_dir, "plastic_uniaxial.npz")
        _u, _alpha, _res, coords_fresh, conn_fresh = _run_plastic_uniaxial()

        np.testing.assert_array_equal(coords_fresh, golden["coords"])
        np.testing.assert_array_equal(conn_fresh, golden["conn"])

    def test_golden_plastic_material_params(self, golden_dir: Path) -> None:
        """Material parameters stored in golden file match the problem definition."""
        golden = _load_golden(golden_dir, "plastic_uniaxial.npz")

        assert float(golden["E"]) == pytest.approx(200.0e3)
        assert float(golden["nu"]) == pytest.approx(0.3)
        assert float(golden["sigma_y0"]) == pytest.approx(250.0)
        assert float(golden["K"]) == pytest.approx(1000.0)
        assert float(golden["n_hard"]) == pytest.approx(1.0)


# ===========================================================================
# Test 4: Drift detection — perturbed golden
# ===========================================================================


class TestGoldenDriftDetection:
    """Verify that the test infrastructure catches deliberate perturbations."""

    def test_golden_drift_detection(self, golden_dir: Path, tmp_path: Path) -> None:
        """Intentionally perturb golden displacement and verify detection.

        Creates a temporary copy of the golden file with the displacement
        perturbed by 1e-6, then checks that comparison would fail.
        """
        # Load the real golden data
        original = _load_golden(golden_dir, "elastic_cantilever.npz")

        perturbed_dir = tmp_path / "golden_perturbed"
        perturbed_dir.mkdir()

        perturbed_disp = original["displacement"].copy()
        perturbed_disp[0, 0] += 1e-6  # add detectable perturbation

        np.savez_compressed(
            perturbed_dir / "elastic_cantilever.npz",
            displacement=perturbed_disp,
            residual_history=original["residual_history"],
            coords=original["coords"],
            conn=original["conn"],
            lam=original["lam"],
            mu=original["mu"],
        )

        # Run fresh solver
        u_fresh, _res, _coords, _conn = _run_elastic_cantilever()

        # The comparison should FAIL against the perturbed golden data
        perturbed_golden = _load_golden(perturbed_dir, "elastic_cantilever.npz")
        with pytest.raises(AssertionError, match="Perturbed golden"):
            np.testing.assert_allclose(
                u_fresh,
                perturbed_golden["displacement"],
                rtol=_RTOL_DISP,
                atol=_ATOL_DISP,
                err_msg="Perturbed golden must not match fresh solve",
            )


# ===========================================================================
# Test 5: Missing / corrupt golden file error handling
# ===========================================================================


class TestGoldenLoadErrors:
    """Golden file loading must produce clear error messages."""

    def test_golden_load_missing_file(self, tmp_path: Path) -> None:
        """Missing golden file raises FileNotFoundError with instructions."""
        with pytest.raises(FileNotFoundError, match="Golden file not found"):
            _load_golden(tmp_path, "nonexistent.npz")

    def test_golden_load_missing_contains_regen_hint(self, tmp_path: Path) -> None:
        """Error message includes the regeneration command."""
        with pytest.raises(FileNotFoundError, match="generate_golden"):
            _load_golden(tmp_path, "nonexistent.npz")

    def test_golden_load_corrupt_file(self, tmp_path: Path) -> None:
        """Corrupt .npz file raises an error on load."""
        corrupt_path = tmp_path / "corrupt.npz"
        corrupt_path.write_bytes(b"this is not a valid npz file")

        with pytest.raises((ValueError, OSError)):
            _load_golden(tmp_path, "corrupt.npz")

    def test_golden_load_missing_key(self, golden_dir: Path) -> None:
        """Accessing a non-existent key in golden data raises KeyError."""
        golden = _load_golden(golden_dir, "elastic_cantilever.npz")
        with pytest.raises(KeyError):
            _ = golden["nonexistent_key"]


# ===========================================================================
# Test 6: Necking bar golden regression
# ===========================================================================


class TestGoldenNeckingBarMatches:
    """Verify necking bar reference data integrity (Task P3-3).

    Acceptance criteria covered:
      AC1: Reference data contains displacement and force arrays
      AC2: Reference data includes mesh_params and material_params
      AC3: Fine mesh solution converges at all load steps
    """

    def test_golden_necking_bar_keys(self, golden_dir: Path) -> None:
        """Verify reference .npz contains required keys.

        Acceptance criterion: P3-3 AC1 + AC2
        Passes when: displacement, force, mesh, and material params present.
        """
        path = golden_dir / "necking_bar_reference.npz"
        if not path.exists():
            pytest.skip("golden file not generated")
        data = np.load(path)

        # Displacement + load-displacement curve
        assert "displacement" in data.files
        assert "force_history" in data.files
        assert "disp_history" in data.files

        # Mesh
        assert "coords" in data.files
        assert "conn" in data.files
        for key in ("nx", "ny", "nz"):
            assert key in data.files, f"missing mesh density key: {key}"

        # Material params (J2 power-law)
        for key in ("E", "nu", "sigma_y0", "K", "n_hard"):
            assert key in data.files, f"missing material param: {key}"

        # Residual history (ragged storage, same pattern as plastic_uniaxial)
        assert "residual_history_flat" in data.files
        assert "residual_step_lengths" in data.files

        # Shape consistency
        u = data["displacement"]
        coords = data["coords"]
        assert u.shape == coords.shape, (
            f"displacement shape {u.shape} != coords shape {coords.shape}"
        )

        n_steps = int(data["residual_step_lengths"].shape[0])
        assert data["force_history"].shape == (n_steps,)
        assert data["disp_history"].shape == (n_steps,)

    def test_golden_necking_bar_convergence(self, golden_dir: Path) -> None:
        """Verify Newton converged at every load step.

        Acceptance criterion: P3-3 AC3
        Passes when: each step's final residual is below a reasonable
        absolute floor and the residual sequence makes progress from its
        initial value.
        """
        path = golden_dir / "necking_bar_reference.npz"
        if not path.exists():
            pytest.skip("golden file not generated")
        data = np.load(path)

        flat = data["residual_history_flat"]
        lengths = data["residual_step_lengths"]

        # Reconstruct per-step residual sequences from ragged storage
        idx = 0
        for step_idx, length in enumerate(lengths):
            step_residuals = flat[idx : idx + int(length)]
            idx += int(length)

            assert len(step_residuals) >= 1, f"step {step_idx} has no residuals"

            # Final residual must be small enough that Newton did not diverge.
            # The ref solver uses tol=1e-8 * R0 so the final absolute residual
            # should be orders of magnitude below the initial.
            r0 = float(step_residuals[0])
            rf = float(step_residuals[-1])
            if r0 > 1e-15:
                reduction = rf / r0
                assert reduction < 1e-6, (
                    f"step {step_idx}: Newton did not reduce residual enough "
                    f"(R0={r0:.3e}, Rf={rf:.3e}, reduction={reduction:.3e})"
                )

        # Monotonic loading → monotonic displacement history
        disp = data["disp_history"]
        assert np.all(np.diff(disp) > 0), "disp_history should be strictly increasing"

        # Non-trivial plastic deformation — force history should show growth
        # beyond the initial elastic response (it's not required to be monotonic
        # everywhere, but the final force must be greater than the first).
        force = np.abs(data["force_history"])
        assert force[-1] > force[0], (
            f"final reaction force {force[-1]:.3e} not greater than "
            f"initial {force[0]:.3e} — expected growth under monotonic loading"
        )
