"""Task P6-1: Add an optional ``algo2code``-generated PCG path behind ``LinearSolverInterface``.

Phase 6 (R5.1) — integration-tier acceptance: prove that a Preconditioned
Conjugate Gradient solver whose body is generated by the sibling ``algo2code``
package can be plugged into the Newton driver via the existing
``LinearSolverInterface`` Protocol, without ``algo2code`` taking a runtime
dependency on ``mechdsl``.

Acceptance criteria:
  1. Integration test proves a generated PCG path can satisfy the solver interface.
  2. All deliverables for P6-1 are in place at the surfaces listed
     (``solver/import_adapter.py``, solver integration layer, ``algo2code``
     interface hook).
  3. No regressions on the existing test suite.

Plan reference: ``dev/plans/recovery_plan_latex_contract.md`` (Phase 6, R5.1, line 317).

Surfaces under test:
  * ``packages/mechdsl-core/src/mechdsl/solver/import_adapter.py`` — new
    ``Algo2CodePCGSolver`` (or equivalent) adapter satisfying
    ``LinearSolverInterface``.
  * Solver integration layer — wiring the generated PCG into the Newton driver.
  * ``packages/algo2code/`` interface hook — the symbol/entry-point that emits
    the PCG body without importing ``mechdsl``.
"""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np
import pytest

from mechdsl.solver import Algo2CodePCGSolver as _Algo2CodePCGSolverFromPkg
from mechdsl.solver.import_adapter import (
    Algo2CodePCGSolver,
    CGSolver,
    LinearSolverInterface,
    PCGSolver,
)


def _spd_tridiagonal(n: int) -> np.ndarray:
    """Build the standard 1D Laplacian-style SPD tridiagonal `[2, -1; -1, 2; ...]`."""
    A = 2.0 * np.eye(n, dtype=np.float64)
    A -= np.eye(n, k=1, dtype=np.float64)
    A -= np.eye(n, k=-1, dtype=np.float64)
    return A


def _matvec(A: np.ndarray):
    def mv(v: np.ndarray) -> np.ndarray:
        return A @ v

    return mv


class TestP6_1:
    """Tests for Task P6-1: optional algo2code-generated PCG behind LinearSolverInterface."""

    @pytest.mark.integration
    def test_generated_pcg_satisfies_solver_interface(self) -> None:
        """P6-1-c1: Integration test proves a generated PCG path can satisfy the solver interface.

        Verifies that the algo2code-emitted PCG implementation, once wrapped
        in its ``solver/import_adapter.py`` adapter, conforms structurally and
        behaviourally to ``LinearSolverInterface``:

        * Duck-typed Protocol conformance via ``hasattr`` and assignability.
        * ``adapter.solve(matvec_fn, rhs, x0, tol, max_iter)`` returns
          ``(solution, iter_count, final_residual_norm)``.
        * On a small SPD test system the returned solution satisfies the
          spec tolerance and converges within reasonable iteration count.
        * With a Jacobi preconditioner, iteration count is no worse than
          unpreconditioned CG (PCG converges no slower than CG for the
          identity-vs-Jacobi case on this well-conditioned tridiagonal).
        """
        # ----- Construct the adapter (no preconditioner). -----
        adapter = Algo2CodePCGSolver()

        # ----- Duck-typed Protocol conformance. -----
        assert hasattr(adapter, "solve"), "adapter must expose a `solve` method"
        # `LinearSolverInterface` is a structural Protocol; assign-then-call
        # is the canonical conformance check (see test_solver.py).
        as_iface: LinearSolverInterface = adapter
        assert callable(as_iface.solve)

        # ----- Build a small SPD test system: 5x5 tridiagonal Laplacian. -----
        n = 5
        A = _spd_tridiagonal(n)
        b = np.arange(1.0, n + 1, dtype=np.float64)
        x_ref = np.linalg.solve(A, b)
        x0 = np.zeros(n, dtype=np.float64)
        tol = 1e-10
        max_iter = 100

        # ----- Solve and unpack the 3-tuple. -----
        result = adapter.solve(_matvec(A), b, x0, tol=tol, max_iter=max_iter)
        assert isinstance(result, tuple) and len(result) == 3, (
            "solve() must return a 3-tuple (x, k, r_norm)"
        )
        x, k, r_norm = result
        assert isinstance(x, np.ndarray)
        assert isinstance(k, int)
        assert isinstance(r_norm, float)

        # ----- Solution accuracy + residual + iteration count. -----
        np.testing.assert_allclose(x, x_ref, atol=1e-8)
        assert float(np.linalg.norm(A @ x - b)) < 1e-8
        assert k > 0, "non-zero RHS should require at least one iteration"
        assert r_norm < 1e-8

        # ----- Class identity: solver/__init__ must re-export the same symbol. -----
        assert _Algo2CodePCGSolverFromPkg is Algo2CodePCGSolver

        # ----- Jacobi-preconditioned PCG must converge no slower than CG. -----
        # Use a 10x10 random SPD system (same recipe as test_solver.py).
        rng = np.random.default_rng(99)
        n2 = 10
        B = rng.standard_normal((n2, n2))
        A2 = B.T @ B + n2 * np.eye(n2)
        b2 = rng.standard_normal(n2).astype(np.float64)
        x_ref2 = np.linalg.solve(A2, b2)
        diag_inv = 1.0 / np.diag(A2)

        def jacobi(v: np.ndarray) -> np.ndarray:
            return diag_inv * v

        adapter_pcg = Algo2CodePCGSolver(precond_fn=jacobi)
        x_pcg, k_pcg, r_pcg = adapter_pcg.solve(
            _matvec(A2), b2, np.zeros(n2), tol=1e-10, max_iter=200
        )
        np.testing.assert_allclose(x_pcg, x_ref2, atol=1e-8)
        assert r_pcg < 1e-10 * float(np.linalg.norm(b2))

        cg = CGSolver()
        _x_cg, k_cg, _r_cg = cg.solve(_matvec(A2), b2, np.zeros(n2), 1e-10, 200)
        assert k_pcg <= k_cg, (
            f"Jacobi-PCG ({k_pcg} iters) must converge no slower than CG ({k_cg} iters)"
        )

        # ----- Behavioural equivalence with the existing PCGSolver. -----
        # Same RHS and SPD system → same converged solution to numerical
        # precision (both algorithms are mathematically identical PCG).
        ref_pcg = PCGSolver(precond_fn=jacobi)
        x_ref_pcg, _, _ = ref_pcg.solve(_matvec(A2), b2, np.zeros(n2), 1e-10, 200)
        np.testing.assert_allclose(x_pcg, x_ref_pcg, atol=1e-8)

    @pytest.mark.integration
    def test_p6_1_deliverables_present_at_listed_surfaces(self) -> None:
        """P6-1-c2: deliverables present at the listed surfaces.

        Verifies by reflection that:

        * ``mechdsl.solver.import_adapter`` exposes the generated-PCG adapter
          symbol ``Algo2CodePCGSolver`` at module level.
        * The Newton-driver / solver integration layer can resolve the
          generated PCG as a ``LinearSolverInterface`` implementation
          (re-exported through ``mechdsl.solver``).
        * The ``algo2code`` package exposes the PCG-emission entry point used
          by the adapter, and ``algo2code`` does **not** import ``mechdsl``
          (runtime-free sibling package invariant from ``.claude/CLAUDE.md``).
        """
        # ── (1) Adapter symbol present in solver/import_adapter.py. ──────
        from mechdsl.solver import import_adapter as _ia

        assert hasattr(_ia, "Algo2CodePCGSolver"), (
            "Algo2CodePCGSolver must be exposed in mechdsl.solver.import_adapter"
        )
        assert _ia.Algo2CodePCGSolver is Algo2CodePCGSolver

        # ── (2) Solver integration layer re-exports the symbol. ──────────
        from mechdsl import solver as _solver_pkg

        assert hasattr(_solver_pkg, "Algo2CodePCGSolver")
        assert "Algo2CodePCGSolver" in _solver_pkg.__all__
        assert _solver_pkg.Algo2CodePCGSolver is Algo2CodePCGSolver

        # The adapter must satisfy the Newton-driver `linear_solver=` slot:
        # the slot expects a `LinearSolverInterface`, and the adapter is
        # constructible with no arguments.
        from mechdsl.solver.newton import newton_solve  # noqa: F401  (presence)

        adapter = Algo2CodePCGSolver()
        as_iface: LinearSolverInterface = adapter
        assert callable(as_iface.solve)

        # ── (3) algo2code interface hook is importable. ──────────────────
        import algo2code
        from algo2code.library.pcg import (
            PCG_ALGORITHM_LATEX,
            get_pcg_algorithm_latex,
        )

        assert hasattr(algo2code, "get_pcg_algorithm_latex")
        assert algo2code.get_pcg_algorithm_latex is get_pcg_algorithm_latex
        assert isinstance(PCG_ALGORITHM_LATEX, str)

        # The hook must return the canonical algorithm verbatim, including
        # the leading directive comments and the algorithmic environment.
        latex = get_pcg_algorithm_latex()
        assert latex.startswith("% algorithm pcg"), (
            "canonical LaTeX must start with the % algorithm directive"
        )
        assert "% backend taichi" in latex
        assert r"\begin{algorithmic}" in latex
        assert r"\end{algorithmic}" in latex
        assert r"apply\_M\_inv" in latex, (
            "canonical LaTeX must use the `apply_M_inv` callable name (P6-1 fix)"
        )

        # The adapter must store the canonical source verbatim.
        assert adapter.algorithm_source == latex

        # ── (4) algo2code stays runtime-free of mechdsl. ─────────────────
        algo2code_src = Path(__file__).resolve().parents[4] / "algo2code" / "src" / "algo2code"
        assert algo2code_src.is_dir(), f"expected algo2code source dir at {algo2code_src}"
        offenders: list[tuple[Path, int, str]] = []
        pattern = re.compile(r"^\s*(?:import\s+mechdsl|from\s+mechdsl)")
        for py_file in algo2code_src.rglob("*.py"):
            text = py_file.read_text(encoding="utf-8")
            for lineno, line in enumerate(text.splitlines(), start=1):
                if pattern.match(line):
                    offenders.append((py_file, lineno, line.rstrip()))
        assert not offenders, (
            "algo2code must not import mechdsl (runtime-free sibling "
            f"invariant). Offending lines: {offenders}"
        )


class TestAlgo2CodePCGSolverFailurePaths:
    """Failure-route coverage for ``Algo2CodePCGSolver`` per the canonical LaTeX.

    These tests pin down the four non-happy-path branches that the canonical
    PCG algpseudocode specifies:

    * Zero-RHS short-circuit (``\\If{$r_0 = 0$} \\Return $x, 0, 0$ \\EndIf``).
    * Identity-preconditioner fallback when ``precond_fn=None`` (the
      ``apply_M_inv = lambda v: v.copy()`` adapter-init binding).
    * Breakdown guard (``\\If{$|pq| < 10^{-300}$} \\State \\textbf{break}``)
      → returns the trailing ``(x, max_iter, ||r||)`` tuple after a
      ``RuntimeWarning``.
    * Max-iter exhaustion → falls through the for-loop and returns the
      trailing tuple unchanged.
    """

    def test_zero_rhs_short_circuit(self) -> None:
        """Per LaTeX: ``\\If{$r_0 = 0$} \\Return $x, 0, 0$``."""
        n = 4
        A = np.eye(n, dtype=np.float64)
        b = np.zeros(n, dtype=np.float64)
        x0 = np.zeros(n, dtype=np.float64)

        solver = Algo2CodePCGSolver()
        x, k, r = solver.solve(_matvec(A), b, x0, tol=1e-12, max_iter=100)

        np.testing.assert_allclose(x, np.zeros(n), atol=1e-15)
        assert k == 0
        assert r == 0.0

    def test_precond_none_uses_identity(self) -> None:
        """``precond_fn=None`` ⇒ ``apply_M_inv = lambda v: v.copy()`` at init.

        With identity preconditioning, results match the unpreconditioned
        ``CGSolver`` on the same SPD system.
        """
        n = 5
        A = _spd_tridiagonal(n)
        b = np.arange(1.0, n + 1, dtype=np.float64)
        x0 = np.zeros(n, dtype=np.float64)

        solver = Algo2CodePCGSolver(precond_fn=None)
        x, _, _ = solver.solve(_matvec(A), b, x0, 1e-10, 100)

        cg = CGSolver()
        x_cg, _, _ = cg.solve(_matvec(A), b, x0, 1e-10, 100)

        np.testing.assert_allclose(x, x_cg, atol=1e-10)

    def test_breakdown_guard_emits_runtime_warning(self) -> None:
        """Non-SPD matvec triggers the ``|pq| < 1e-300`` guard.

        We construct a degenerate matvec where ``A @ p == 0`` for any
        non-trivial ``p`` (the zero matrix), which forces ``pq = 0`` on the
        first iteration.  The adapter must emit a ``RuntimeWarning`` and
        return the trailing 3-tuple from the LaTeX's final ``\\Return``.
        """
        n = 3

        def zero_matvec(v: np.ndarray) -> np.ndarray:
            return np.zeros_like(v)

        b = np.array([1.0, 2.0, 3.0], dtype=np.float64)
        x0 = np.zeros(n, dtype=np.float64)

        solver = Algo2CodePCGSolver()
        with pytest.warns(RuntimeWarning, match="breakdown"):
            x, k, r = solver.solve(zero_matvec, b, x0, tol=1e-10, max_iter=50)

        # After breakdown the loop returns the trailing maxiter return per
        # the canonical LaTeX. `x` is unchanged (we never updated it).
        assert k == 50
        np.testing.assert_allclose(x, x0)
        # `r` reflects ||rhs - A x|| = ||b|| since A x = 0 and x = x0 = 0.
        assert r == pytest.approx(float(np.linalg.norm(b)))

    def test_max_iter_exhausted_returns_trailing_tuple(self) -> None:
        """If convergence is not reached, the for-loop completes and the
        adapter returns ``(x, maxiter, ||r||_2)`` per the trailing
        ``\\Return`` line.
        """
        n = 5
        A = _spd_tridiagonal(n)
        b = np.arange(1.0, n + 1, dtype=np.float64)
        x0 = np.zeros(n, dtype=np.float64)

        solver = Algo2CodePCGSolver()
        # Tight tolerance + 1 iteration → cannot converge.
        x, k, r = solver.solve(_matvec(A), b, x0, tol=1e-16, max_iter=1)
        assert k == 1
        # Residual is positive and finite — the trailing return reports it.
        assert r > 0.0
        assert np.isfinite(r)
        # The reported residual matches the actual ||A x - b||.
        actual = float(np.linalg.norm(A @ x - b))
        np.testing.assert_allclose(r, actual, rtol=1e-10)

    def test_callable_preconditioner_is_invoked_each_iteration(self) -> None:
        """Verify the ``apply_M_inv(r)`` callable is actually called.

        We wrap the Jacobi preconditioner in a counter and assert it fires
        at least once per iteration of a non-trivial solve (twice on the
        first iteration: once for ``z = apply_M_inv(r)`` before the loop,
        once for ``z = apply_M_inv(r)`` inside the loop after ``r`` is
        updated).
        """
        n = 5
        A = _spd_tridiagonal(n)
        b = np.arange(1.0, n + 1, dtype=np.float64)
        x0 = np.zeros(n, dtype=np.float64)
        diag_inv = 1.0 / np.diag(A)
        calls = {"n": 0}

        def jacobi(v: np.ndarray) -> np.ndarray:
            calls["n"] += 1
            return diag_inv * v

        solver = Algo2CodePCGSolver(precond_fn=jacobi)
        _x, k, _r = solver.solve(_matvec(A), b, x0, tol=1e-10, max_iter=100)
        # Pre-loop application + at least k-1 in-loop applications.
        # (Convergence return on iteration k skips the final precond call.)
        assert calls["n"] >= max(1, k)
