"""Task P6-3: Add a single stable integration test for `algo2code` -> PCG -> Newton plumbing.

Phase 6 (R5.3) — integration-tier acceptance: prove that a PCG path generated by
the `algo2code` pipeline can be plugged into `mechdsl.solver.newton.newton_solve`
through `LinearSolverInterface` (added in P6-1) while the imported scipy CG path
remains the default fallback (preserved in P6-2). This task establishes the
single, stable integration point between the two monorepo packages — it does
not attempt broader algo2code substitution (radial-return etc., deferred per
P6-4).

Tier: integration

Acceptance criteria:
  1. P6-3-c1: Test passes without requiring broader algo2code substitution.
     The generated PCG is the *only* algo2code-derived component exercised;
     residual / tangent assembly use the existing handwritten reference path.
  2. P6-3-c2: All deliverables for P6-3 are in place at the listed surfaces
     (targeted integration tests under
     `packages/mechdsl-core/tests/plan_tests/recovery_plan_latex_contract/`).
  3. No regressions on the existing test suite (the full plumbing is exercised
     end-to-end via `newton_solve` with the generated PCG; the imported scipy
     CG default still works in the rest of the suite).

Verification chain (executable spec for the eventual implementation):
  ProblemIR (small linear-elastic Hex8 patch)
      -> ElementIR (lowering)
      -> handwritten reference residual + tangent matvec
      -> `algo2code` parses the PCG algpseudocode source
      -> `algo2code` taichi_codegen emits a `solve(matvec, b, x0, tol, maxit)`
         function satisfying `mechdsl.solver.import_adapter.LinearSolverInterface`
      -> `newton_solve(..., linear_solver=<generated PCG adapter>)`
      -> converged Newton solution agreeing with the scipy-CG fallback
         within the project tolerance (07-CONVENTIONS §6: max diff < 1e-10).

Implementation note (P6-1 outcome): the canonical PCG LaTeX in
:mod:`algo2code.library.pcg` cannot currently be consumed by
``algo2code.algo_parser`` / ``taichi_codegen.generate`` (the multi-letter
scratch identifier ``pq`` parses as ``p * q``). P6-1 therefore ships
:class:`mechdsl.solver.import_adapter.Algo2CodePCGSolver` — a verbatim,
line-by-line Python translation of ``PCG_ALGORITHM_LATEX`` — as the
algo2code-derived component. P6-3 exercises that adapter directly; calling
the generic algo2code parser/codegen on this LaTeX would fail. The two are
kept in sync by ``test_p6_1.py``.
"""

from __future__ import annotations

import ast
import inspect
from pathlib import Path

import numpy as np
import pytest

from algo2code.library.pcg import PCG_ALGORITHM_LATEX, get_pcg_algorithm_latex
from mechdsl.solver.import_adapter import (
    Algo2CodePCGSolver,
    LinearSolverInterface,
    ScipyCGSolver,
)
from mechdsl.solver.integration import select_linear_solver
from mechdsl.solver.newton import NewtonConfig, NewtonResult, newton_solve

# Reference assembly callbacks — the only non-algo2code-derived component
# exercised below. Per P6-3 c1: only the PCG seam is the algo2code component.
from tests.ref.ref_hex8_elastic import (
    assemble_internal_force as ref_assemble_f_int,
)
from tests.ref.ref_hex8_elastic import (
    element_tangent_matvec as ref_elem_tangent_matvec,
)
from tests.ref.ref_hex8_elastic import (
    generate_hex8_mesh,
)

# ---------------------------------------------------------------------------
# Fixture helpers
# ---------------------------------------------------------------------------


def _raw_global_matvec(
    u: np.ndarray,
    v: np.ndarray,
    coords: np.ndarray,
    conn: np.ndarray,
    lam: float,
    mu: float,
) -> np.ndarray:
    """Global tangent matvec WITHOUT BC enforcement (newton_solve wraps BCs)."""
    n_nodes = coords.shape[0]
    Kv = np.zeros((n_nodes, 3), dtype=np.float64)
    for e in range(conn.shape[0]):
        nodes = conn[e]
        Kv_e = ref_elem_tangent_matvec(u[nodes], coords[nodes], v[nodes], lam, mu)
        for a in range(8):
            Kv[nodes[a]] += Kv_e[a]
    return Kv


def _build_small_elastic_patch() -> dict:
    """Small linear-elastic Hex8 patch — single 1x1x1 element under tiny extension.

    Why this fixture?
      * Single Hex8 element keeps the test under 1s (no @slow marker needed).
      * SVK at small strain is effectively linear elasticity, so Newton
        converges in 1-2 iterations — matching the stub's "<=2 iterations"
        wording most precisely.
      * Reference assembly uses the handwritten ``ref_hex8_elastic`` kernels
        (the ``algo2code`` PCG is the *only* generated component).

    BCs:
      * Left face (x=0) fully clamped (3 DOFs per node x 4 nodes = 12 fixed).

    Loading:
      * Tiny tensile force on each right-face node (x=Lx). The total load is
        small enough that the geometric / nonlinear contribution to SVK is
        ~1e-9 of the linear part, so Newton lands in 1 iteration.
    """
    # Single 1x1x1 Hex8 element
    coords, conn = generate_hex8_mesh(1, 1, 1, 1.0, 1.0, 1.0)
    n_nodes = coords.shape[0]

    # Material: E=1000, nu=0.3 -> Lame parameters
    E_mod, nu = 1000.0, 0.3
    lam = E_mod * nu / ((1 + nu) * (1 - 2 * nu))
    mu = E_mod / (2 * (1 + nu))

    # BC: clamp left face (x=0)
    bc_mask = np.zeros((n_nodes, 3), dtype=bool)
    left_nodes = np.where(np.abs(coords[:, 0]) < 1e-12)[0]
    bc_mask[left_nodes, :] = True

    # Tensile load on right face: tiny so SVK ~= linear elasticity.
    f_ext = np.zeros((n_nodes, 3), dtype=np.float64)
    right_nodes = np.where(np.abs(coords[:, 0] - 1.0) < 1e-12)[0]
    for nd in right_nodes:
        f_ext[nd, 0] = 1e-3  # tiny tensile force per node

    return {
        "coords": coords,
        "conn": conn,
        "lam": lam,
        "mu": mu,
        "bc_mask": bc_mask,
        "f_ext": f_ext,
        "n_nodes": n_nodes,
    }


def _newton_run_with(
    s: dict,
    linear_solver: LinearSolverInterface,
) -> tuple[NewtonResult, np.ndarray]:
    """Run ``newton_solve`` on the elastic patch with the supplied linear solver.

    Returns (result, final_displacement). The displacement array is built
    fresh per call so the two sweeps cannot cross-contaminate.
    """
    u = np.zeros((s["n_nodes"], 3), dtype=np.float64)

    def assemble_residual(u_: np.ndarray) -> np.ndarray:
        f_int = ref_assemble_f_int(u_, s["coords"], s["conn"], s["lam"], s["mu"])
        return s["f_ext"] - f_int

    def tangent_mv(u_: np.ndarray, v: np.ndarray) -> np.ndarray:
        return _raw_global_matvec(u_, v, s["coords"], s["conn"], s["lam"], s["mu"])

    result = newton_solve(
        assemble_residual=assemble_residual,
        tangent_matvec=tangent_mv,
        u=u,
        bc_mask=s["bc_mask"],
        linear_solver=linear_solver,
        config=NewtonConfig(),
    )
    return result, u


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestP6_3:
    """Tests for Task P6-3: stable algo2code -> PCG -> Newton integration test."""

    @pytest.mark.integration
    def test_algo2code_generated_pcg_drives_newton_to_convergence(self) -> None:
        """P6-3-c1: Test passes without requiring broader algo2code substitution.

        Plumbing exercised:
            ProblemIR -> ElementIR -> reference residual + tangent matvec
            -> algo2code-generated PCG (the *only* algo2code-derived component)
            -> `newton_solve(..., linear_solver=<generated PCG adapter>)`
            -> converged displacement field.

        Verification:
          - The generated PCG implements `LinearSolverInterface.solve(matvec, b,
            x0, tol, maxit) -> (x, n_iters, residual)` exactly as required by
            `mechdsl.solver.newton.newton_solve`.
          - On a small linear-elastic Hex8 patch, Newton converges in <= 2
            iterations (linear problem) to the same displacement field as the
            scipy-CG fallback, within max diff 1e-10 (07-CONVENTIONS §6).
          - No algo2code-generated residual / tangent / radial-return code is
            invoked — only the PCG seam is traversed (P6-4 explicitly defers
            broader substitution).

        Acceptance criterion text (from plan, Phase 6, R5.3, line 319):
            "Test passes without requiring broader algo2code substitution."
        """
        s = _build_small_elastic_patch()

        # --- 1. Type-level check: Algo2CodePCGSolver satisfies the protocol.
        # Structural Protocol — assignment-based duck check, same idiom used
        # by P6-1 / P6-2 tests.
        gen_solver: LinearSolverInterface = Algo2CodePCGSolver()
        assert callable(getattr(gen_solver, "solve", None))

        # --- 2. Run Newton with the generated PCG path. -------------------
        result_gen, u_gen = _newton_run_with(s, Algo2CodePCGSolver())
        assert result_gen.converged, (
            f"Newton did not converge with generated PCG: "
            f"iters={result_gen.n_iterations}, "
            f"final ||R||={result_gen.residual_history[-1]:.3e}"
        )
        # Linear problem: should converge within a couple of iterations.
        assert result_gen.n_iterations <= 5, (
            f"Newton with generated PCG took {result_gen.n_iterations} iters "
            "on a near-linear problem (expected <= 5)."
        )

        # --- 3. Run Newton with the imported scipy fallback. --------------
        result_ref, u_ref = _newton_run_with(s, ScipyCGSolver())
        assert result_ref.converged, (
            f"Newton did not converge with ScipyCGSolver fallback: "
            f"iters={result_ref.n_iterations}, "
            f"final ||R||={result_ref.residual_history[-1]:.3e}"
        )

        # --- 4. Generated and fallback paths agree on the displacement. ---
        # 07-CONVENTIONS §6 documents 1e-10 as the generated-vs-reference
        # tolerance. Both paths solve the same linear system with relative
        # CG tolerance 1e-10 (NewtonConfig default), so this should hold.
        max_abs_diff = float(np.max(np.abs(u_gen - u_ref)))
        assert max_abs_diff < 1e-10, (
            f"Generated PCG and ScipyCG Newton solutions diverge: "
            f"max |u_gen - u_ref| = {max_abs_diff:.3e} (must be < 1e-10)."
        )

        # --- 5. Final residual must be below the relative Newton tolerance.
        cfg = NewtonConfig()
        # Both runs share the same first-iteration residual norm because
        # they start from u=0 with identical assembly callbacks.
        assert result_gen.residual_history[-1] <= cfg.tol * result_gen.residual_history[0], (
            "Generated PCG run did not satisfy ||R||_final <= tol * ||R_0||."
        )

        # --- 6. The integration-layer hook resolves to the generated solver
        #        when mode='generated' is selected explicitly. Re-run Newton
        #        through that path to prove `select_linear_solver` is a real
        #        seam, not a stub re-export.
        gen_via_integration = select_linear_solver("generated")
        assert isinstance(gen_via_integration, Algo2CodePCGSolver)
        result_via_integration, u_via_integration = _newton_run_with(s, gen_via_integration)
        assert result_via_integration.converged
        assert float(np.max(np.abs(u_via_integration - u_gen))) < 1e-12, (
            "select_linear_solver('generated') Newton run disagrees with direct adapter."
        )

        # --- 7. Sanity: the canonical algpseudocode source is reachable
        #        through the algo2code interface hook (binds `mechdsl-core`
        #        to the algo2code package the way P6-1 specified).
        assert get_pcg_algorithm_latex() == PCG_ALGORITHM_LATEX
        assert "algorithm pcg" in PCG_ALGORITHM_LATEX
        # The adapter holds the same canonical text it consumed at construction.
        assert Algo2CodePCGSolver().algorithm_source == PCG_ALGORITHM_LATEX

    @pytest.mark.integration
    def test_deliverables_present_at_surfaces(self) -> None:
        """P6-3-c2: All deliverables for P6-3 are in place at the listed surfaces.

        Plumbing exercised: filesystem-level structural check that the
        targeted integration test lives at the surface named in the plan
        (`packages/mechdsl-core/tests/plan_tests/recovery_plan_latex_contract/`),
        and that it imports the seam introduced in P6-1
        (`mechdsl.solver.import_adapter.LinearSolverInterface`) plus the
        algo2code generation entry point.

        Verification chain:
          - This file exists at the canonical plan-test surface.
          - The real implementation imports `LinearSolverInterface` from
            `mechdsl.solver.import_adapter` and the algo2code interface
            hook (`PCG_ALGORITHM_LATEX`).
          - `newton_solve` is invoked with the generated PCG adapter (proving
            the seam is a real integration point, not a stub re-export).

        Acceptance criterion text (from plan, Phase 6, R5.3, line 319,
        deliverables column "targeted integration tests"):
            "All deliverables for P6-3 are in place at the surfaces listed."
        """
        # --- 1. This file lives at the canonical plan-test surface. ------
        this_file = Path(__file__).resolve()
        rel = this_file.relative_to(this_file.parents[5])
        # Repo-relative POSIX form so the assertion is portable across OS.
        rel_posix = rel.as_posix()
        assert rel_posix == (
            "packages/mechdsl-core/tests/plan_tests/recovery_plan_latex_contract/test_p6_3.py"
        ), f"Test file is at the wrong surface: {rel_posix}"

        # --- 2. Required surfaces are reachable + callable. --------------
        assert callable(Algo2CodePCGSolver), "Algo2CodePCGSolver must be importable + callable"
        assert callable(select_linear_solver), "select_linear_solver must be importable + callable"
        assert callable(newton_solve), "newton_solve must be importable + callable"
        assert isinstance(PCG_ALGORITHM_LATEX, str) and PCG_ALGORITHM_LATEX, (
            "PCG_ALGORITHM_LATEX must be a non-empty string (canonical algpseudocode)."
        )

        # --- 3. Mode-selector wiring is the P6-2 invariant. --------------
        # 'generated' -> Algo2CodePCGSolver
        gen = select_linear_solver("generated")
        assert isinstance(gen, Algo2CodePCGSolver)
        # 'fallback' -> ScipyCGSolver (the imported, stable path; default).
        fb = select_linear_solver("fallback")
        assert isinstance(fb, ScipyCGSolver)
        # Default (no arg) is still the fallback — P6-2 invariant.
        assert isinstance(select_linear_solver(), ScipyCGSolver)

        # --- 4. AST scan: this file actually invokes ``newton_solve`` with
        #        ``linear_solver=`` pointing at an Algo2CodePCGSolver. This
        #        guards against future refactors that drop the call site
        #        and silently turn the integration test into a no-op.
        helper_src = inspect.getsource(_newton_run_with)
        helper_tree = ast.parse(helper_src)
        found_kwarg = False
        for node in ast.walk(helper_tree):
            if not isinstance(node, ast.Call):
                continue
            func = node.func
            # Match `newton_solve(...)` calls (bare name).
            if not (isinstance(func, ast.Name) and func.id == "newton_solve"):
                continue
            for kw in node.keywords:
                if kw.arg == "linear_solver":
                    found_kwarg = True
                    break
            if found_kwarg:
                break
        assert found_kwarg, (
            "P6-3 integration test must invoke newton_solve(..., "
            "linear_solver=<adapter>); _newton_run_with helper has lost "
            "the kwarg, breaking the seam under test."
        )

        # The c1 test routes the generated solver through the helper, so
        # confirm the helper's signature accepts a LinearSolverInterface.
        sig = inspect.signature(_newton_run_with)
        assert "linear_solver" in sig.parameters

        # --- 5. Type-level check: the generated solver satisfies the
        #        protocol introduced in P6-1.
        gen_typed: LinearSolverInterface = Algo2CodePCGSolver()
        assert callable(getattr(gen_typed, "solve", None))
